apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-app-pvc
spec:
  storageClassName: image-app-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
