apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-deploy
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: ping_pong:ex-2.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres-svc:5432/postgres"
