apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-postgres
  namespace: project
spec:
  serviceName: todo-postgres-svc
  replicas: 1

  selector:
    matchLabels:
      app: todo-postgres

  template:
    metadata:
      labels:
        app: todo-postgres

    spec:
      containers:
        - name: postgres
          image: postgres:16

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_PASSWORD
              value: postgres

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: postgres-data

      spec:
        accessModes:
          - ReadWriteOnce

        storageClassName: local-path

        resources:
          requests:
            storage: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: todo-postgres-svc
  namespace: project
spec:
  selector:
    app: todo-postgres
  ports:
    - port: 5432
      targetPort: 5432
